version: '3.4'

services:
  taskmanager.api:
    image: ${DOCKER_REGISTRY-}taskmanagerapi
    build:
      context: .
      dockerfile: TaskManager.Api/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  proxy:
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  client:
    image: client 
    ports:
      - "5001:3000"
    environment:
      - NODE_ENV=production
      - WDS_SOCKET_PORT=0
    build:
      context: ./task_manager_client
      dockerfile: Dokerfile

  

